#%RAML 1.0
title: Martian Motel
version: 1.0
baseUri: http://martianmotel.ddns.net/api
types:
  Password:
    minLength: 8
  Phone:
    pattern: ^[0-9()-]+$
  Reservation:
    properties:
      userEmail: string
      roomType:
        properties:
          name: string
          desc: string
          space: integer
      startDate: datetime
      endDate: datetime
      numGuests: integer
      price: number
  User:
    properties:
      firstname: string
      lastname: string
      dob: datetime
      phone: Phone
      email: string
      address: string
      password: Password
  RoomType:
    properties:
      name: string
      desc: string
      space: integer
  Room:
    properties:
      rmType: RoomType
      num: integer
      avail: boolean
  CreditCard:
    pattern: \b\d{13,16}\b
  CVV:
    pattern: /^[0-9]{3,4}$/
  Payment:
    properties:
      userEmail: string
      num: CreditCard
      exp: datetime
      cvv: CVV
  Login:
    properties:
      username: string
      password: Password
  ResCheck:
    properties:
      type: RoomType | integer #If type is integer it will be treated as space needed
      startDate: datetime
      endDate: datetime
/public/users:
  /authenticate:
    post:
      description: |
        Authenticates users with a email and passord. Returns a JWT token.
      body:
        application/json:
          type: Login
  /register:
    post:
      description: |
        Creates a user with the input.
      body:
        application/json:
          type: User
/public/reservation:
  post:
    description: |
      Creates a reservation based on the parameters passed.
    body:
      application/json:
        type: Reservation
  /check:
    get:
      description: |
        Checks for availability and returns a boolean.
      body:
        application/json:
          type: ResCheck
/protected/users:
  /{user._id}:
    delete:
    put:
    get:
  /current:
/protected/reservation:
/protected/room:
  /type: